AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  RDS_Query

  Sample SAM Template for RDS_Query

Resources:
  RdsFetchAllQueryFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: read.lambda_handler
      Runtime: python3.9
      Timeout: 10
      Architectures:
        - x86_64

  RdsCreateQueryFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: create.lambda_handler
      Runtime: python3.9
      Timeout: 10
      Architectures:
        - x86_64

  RdsUpdateQueryFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: update.lambda_handler
      Runtime: python3.9
      Timeout: 10
      Architectures:
        - x86_64

  RdsDeleteQueryFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: delete.lambda_handler
      Runtime: python3.9
      Timeout: 10
      Architectures:
        - x86_64

  RdsTransactionIDQueryFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: read_id.lambda_handler
      Runtime: python3.9
      Timeout: 10
      Architectures:
        - x86_64